# Generated by Django 3.2.8 on 2021-10-29 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20211029_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowProxy',
            fields=[
            ],
            options={
                'verbose_name': 'TV Shov',
                'verbose_name_plural': 'TV Shows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlist.playlist',),
        ),
        migrations.CreateModel(
            name='TvShowSeasonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlist.playlist',),
        ),
    ]
