# Generated by Django 3.2.8 on 2021-10-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20211029_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlist.playlist',),
        ),
    ]
