# Generated by Django 3.2.8 on 2021-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='video_id',
            field=models.CharField(max_length=220, unique=True),
        ),
    ]
