# Generated by Django 3.2.8 on 2021-10-26 10:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_alter_videocontent_video_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='videocontent',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
