# Generated by Django 3.2.8 on 2021-10-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_alter_videocontent_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='videocontent',
            managers=[
            ],
        ),
    ]
